# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Lawyer.create!(name: "Yasmin Corrêa Mendonça", state: "CE", order: "1")
Lawyer.create!(name: "Arthur Melo Campus", state: "SP", order: "1")
Lawyer.create!(name: "Jesus Fernandéz Guimarães", state: "PE", order: "1")
Lawyer.create!(name: "Bruno Sampaio da Silva", state: "CE", order: "2")
Lawyer.create!(name: "Daiana Paulino Monteiro", state: "RJ", order: "1")
Lawyer.create!(name: "Sabrina Sá Sturdart", state: "RS", order: "1")
Lawyer.create!(name: "Maria Luiza de Souza", state: "RJ", order: "3")
Lawyer.create!(name: "João Paulo de Castro Carneiro", state: "RS", order: "1")
Lawyer.create!(name: "Saulo Rodrigues Londres", state: "SP", order: "2")
Lawyer.create!(name: "Ana Paula de Carvalho Silva", state: "RJ", order: "2")

ce = State.create!(name: "CE", interaction: "1")
rj = State.create!(name: "RJ", interaction: "1")
sp = State.create!(name: "SP", interaction: "1")
rs = State.create!(name: "RS", interaction: "1")
pe = State.create!(name: "PE", interaction: "1")
ac = State.create!(name: "AC", interaction: "1")
al = State.create!(name: "AL", interaction: "1")
ap = State.create!(name: "AP", interaction: "1")
am = State.create!(name: "AM", interaction: "1")
ba = State.create!(name: "BA", interaction: "1")
df = State.create!(name: "DF", interaction: "1")
es = State.create!(name: "ES", interaction: "1")
go = State.create!(name: "GO", interaction: "1")
ma = State.create!(name: "MA", interaction: "1")
mt = State.create!(name: "MT", interaction: "1")
ms = State.create!(name: "MS", interaction: "1")
mg = State.create!(name: "MG", interaction: "1")
pa = State.create!(name: "PA", interaction: "1")
pb = State.create!(name: "PB", interaction: "1")
pr = State.create!(name: "PR", interaction: "1")
pi = State.create!(name: "PI", interaction: "1")
rn = State.create!(name: "RN", interaction: "1")
ro = State.create!(name: "RO", interaction: "1")
rr = State.create!(name: "RR", interaction: "1")
sc = State.create!(name: "SC", interaction: "1")
se = State.create!(name: "SE", interaction: "1")
to = State.create!(name: "TO", interaction: "1")